# Generated by Django 2.0 on 2017-12-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataminer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bourse',
            options={'ordering': ['name'], 'verbose_name': 'биржа', 'verbose_name_plural': 'биржи'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['name'], 'verbose_name': 'валюта', 'verbose_name_plural': 'валюты'},
        ),
        migrations.AlterModelOptions(
            name='pair',
            options={'ordering': ['name'], 'verbose_name': 'валютная пара', 'verbose_name_plural': 'валютные пары'},
        ),
        migrations.AlterField(
            model_name='bourse',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
