# Generated by Django 2.0 on 2017-12-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataminer', '0003_auto_20171224_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='base_url',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
