# Generated by Django 2.0 on 2017-12-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataminer', '0004_currency_base_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='base_url',
        ),
        migrations.AddField(
            model_name='bourse',
            name='base_url',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
