# Generated by Django 2.0 on 2017-12-30 19:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dataminer', '0006_auto_20171229_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairTicker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('high', models.FloatField(default=0.0)),
                ('low', models.FloatField(default=0.0)),
                ('avg', models.FloatField(default=0.0)),
                ('vol', models.FloatField(default=0.0)),
                ('vol_cur', models.FloatField(default=0.0)),
                ('last', models.FloatField(default=0.0)),
                ('buy', models.FloatField(default=0.0)),
                ('sell', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'pair ticker',
                'verbose_name_plural': 'pair tickers',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterField(
            model_name='pair',
            name='fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pairticker',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='dataminer.Pair'),
        ),
    ]
