# Generated by Django 2.0 on 2017-12-31 08:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dataminer', '0008_pairorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairTrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0.0)),
                ('amount', models.FloatField(default=0.0)),
                ('ask', models.BooleanField(default=False)),
                ('bid', models.BooleanField(default=False)),
                ('tid', models.BigIntegerField()),
                ('timestamp', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='dataminer.Pair')),
            ],
            options={
                'verbose_name': 'pair trade',
                'verbose_name_plural': 'pair trades',
                'ordering': ['created_at'],
            },
        ),
        migrations.RenameField(
            model_name='pairorder',
            old_name='vol',
            new_name='amount',
        ),
    ]
