# Generated by Django 2.0 on 2018-01-02 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataminer', '0009_auto_20171231_0811'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pairtrade',
            unique_together={('pair', 'timestamp')},
        ),
    ]
