# Generated by Django 2.0 on 2018-01-02 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataminer', '0010_auto_20180102_1657'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pairtrade',
            unique_together={('pair', 'tid')},
        ),
    ]
