# Generated by Django 2.0 on 2018-01-03 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataminer', '0011_auto_20180102_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairorder',
            name='pair',
        ),
        migrations.AddField(
            model_name='pairorder',
            name='ticker',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dataminer.PairTicker'),
        ),
        migrations.AddField(
            model_name='pairticker',
            name='max_trade_timestamp',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='pairticker',
            name='min_trade_timestamp',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
