# Generated by Django 2.0 on 2018-01-04 07:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dataminer', '0012_auto_20180103_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairJSONInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticker', models.TextField()),
                ('orders', models.TextField()),
                ('trades', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='dataminer.Pair')),
            ],
            options={
                'verbose_name': 'pair json info',
                'verbose_name_plural': 'pair json infos',
                'ordering': ['created_at'],
            },
        ),
    ]
