# Generated by Django 2.0 on 2018-01-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataminer', '0013_pairjsoninfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='fee',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pair',
            name='max_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pair',
            name='max_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pair',
            name='min_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pair',
            name='min_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pair',
            name='min_total',
            field=models.FloatField(null=True),
        ),
    ]
