# Generated by Django 2.0 on 2018-01-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataminer', '0014_auto_20180112_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='max_quantity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pair',
            name='min_quantity',
            field=models.FloatField(null=True),
        ),
    ]
