# Generated by Django 2.0.1 on 2018-01-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataminer', '0015_auto_20180112_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairjsoninfo',
            name='orders',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pairjsoninfo',
            name='ticker',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pairjsoninfo',
            name='trades',
            field=models.TextField(null=True),
        ),
    ]
