# Generated by Django 2.0.1 on 2018-02-02 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataminer', '0017_pairjsoninfo_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PairJSONInfo',
            new_name='PairInfo',
        ),
        migrations.RemoveField(
            model_name='pairorder',
            name='ticker',
        ),
        migrations.RemoveField(
            model_name='pairticker',
            name='pair',
        ),
        migrations.AlterUniqueTogether(
            name='pairtrade',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pairtrade',
            name='pair',
        ),
        migrations.AlterModelOptions(
            name='pairinfo',
            options={'ordering': ['created_at'], 'verbose_name': 'pair info', 'verbose_name_plural': 'pair infos'},
        ),
        migrations.DeleteModel(
            name='PairOrder',
        ),
        migrations.DeleteModel(
            name='PairTicker',
        ),
        migrations.DeleteModel(
            name='PairTrade',
        ),
    ]
