# Generated by Django 2.0.1 on 2018-02-02 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataminer', '0018_auto_20180202_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairinfo',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='pairinfo',
            name='ticker',
        ),
        migrations.RemoveField(
            model_name='pairinfo',
            name='trades',
        ),
    ]
