# Generated by Django 2.0.1 on 2018-02-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataminer', '0019_auto_20180202_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairinfo',
            name='exported_at',
            field=models.DateTimeField(null=True),
        ),
    ]
