# Generated by Django 2.0.2 on 2018-03-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataminer', '0020_pairinfo_exported_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairinfo',
            name='exported_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
